version: "3"

services:

  sonarqube:

    image: sonarqube

    container_name: sonarqube

    restart: unless-stopped

    environment:

      - SONARQUBE_JDBC_USERNAME=admin

      - SONARQUBE_JDBC_PASSWORD=admin

      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube

    ports:

      - "9001:9000"

      - "9092:9092"

    volumes:

      - sonarqube_conf:/opt/sonarqube/conf

      - sonarqube_data:/opt/sonarqube/data

      - sonarqube_extensions:/opt/sonarqube/extensions

      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins


  db:

    image: postgres:10.1

    container_name: db

    restart: unless-stopped

    environment:

      - POSTGRES_USER=admin

      - POSTGRES_PASSWORD=admin

      - POSTGRES_DB=sonarqube

    volumes:

      - sonarqube_db:/var/lib/postgresql10

      - postgresql_data:/var/lib/postgresql10/data

volumes:

  postgresql_data:

  sonarqube_bundled-plugins:

  sonarqube_conf:

  sonarqube_data:

  sonarqube_db:

  sonarqube_extensions: